---

name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Build wheel
        run: poetry build -f wheel
      - name: Add wheel to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/healthy-${{ steps.tag.outputs.version }}-py3-none-any.whl
          asset_name: healthy-${{ steps.tag.outputs.version }}-py3-none-any.whl
          asset_content_type: application/zip
